---

- name: Install Redis
  apt:
    name: redis-server
    state: present

- name: Configure Redis
  template:
    src: redis.conf.j2
    dest: "/etc/redis/redis.conf"
    mode: 0644
  notify: restart redis

- name: Ensure Redis is running
  service:
    name: redis-server
    state: started
    enabled: yes