---

- name: Install kerberos
  apt:
    name: krb5-user
    state: present

- name: Configure kerberos for Geiger realm
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644